### ISSUE TITLE
Notebooks outdated

### ISSUE THREAD

**Issue by mhaeussermann** [UWNETLAB/metaknowledge#10]
First of all: Thank you for your ongoing work on metaknowledge. I've noticed that the notebooks offered in the repository are quite out of date, mostly due to functions and modules being renamed. I experienced this using the notebook 'Making graphs': The second and third code block fail as metaknowledge.visual has been replaced by metaknowledge.contour.plotting and RC.coCiteNetwork() by RC.networkCoCitation(). Due to the fact that the notebooks might be the first entry point for some folks, they should be updated. I assume that this situation is also at the root of issue #8.

**Comment by mclevey** [comment]
Thanks! I agree this is an issue. We are currently doing an extensive updating of the documentation, as well as a new release that will simplify the package and make it easier to get started with.

**Comment by marianapaesf** [comment]
First of all, thank you very much for developing metaknowledge. I am a university professor of engineering in Brazil and I and two students are applying it to mine texts from the Web of Science. However, we had the same problem as Manuel. Since our project has a deadline, could you tell us when the updates will be available? And, if it is not a nuisance, could you help us?

**Comment by mhaeussermann** [comment]
From what I remember, the [documentation](https://metaknowledge.readthedocs.io/en/latest/examples/index.html) is (mostly) up to date, so implementing the steps of the notebooks by yourself should be doable. What is the error message?

**Comment by mhaeussermann** [comment]
> Thanks! I agree this is an issue. We are currently doing an extensive updating of the documentation, as well as preparing a new release that will simplify the package and make it easier to get started with.

As an aside: Is there any way to get involved with the new release as an outside contributor?

**Comment by tcrick** [comment]
> 
> 
> First of all, thank you very much for developing metaknowledge. I am a university professor of engineering in Brazil and I and two students are applying it to mine texts from the Web of Science. However, we had the same problem as Manuel. Since our project has a deadline, could you tell us when the updates will be available? And, if it is not a nuisance, could you help us?

I've finished a rough update to the notebooks so that all the functions used in them should now be working, keeping in mind that they will likely need a more thorough reworking with the new release.

**Comment by tcrick** [comment]
> 
> 
> > Thanks! I agree this is an issue. We are currently doing an extensive updating of the documentation, as well as preparing a new release that will simplify the package and make it easier to get started with.
> 
> As an aside: Is there any way to get involved with the new release as an outside contributor?

We would love some outside contributions, thank you! We'll get in touch when we have time to get it rolling.

**Comment by mclevey** [comment]
> > Thanks! I agree this is an issue. We are currently doing an extensive updating of the documentation, as well as preparing a new release that will simplify the package and make it easier to get started with.
> 
> As an aside: Is there any way to get involved with the new release as an outside contributor?

Absolutely!
