### ISSUE TITLE
writeGraph() column naming

### ISSUE THREAD

**Issue by mhaeussermann** [UWNETLAB/metaknowledge#12]
Right now, the function writeGraph outputs the edge list csv with the columns being labeled "From" and "To". When importing the csv into Gephi, it is not correctly identified as an edge list as Gephi expects the columns to be named "Source" and "Target". Is there a specific reason for the current labeling or would it be reasonable to change this?

**Comment by tcrick** [comment]
This makes sense - networkx also uses that convention. I've made this change in an update, pushed to PyPI. Thanks!

**Comment by mhaeussermann** [comment]
Thanks! Closing this because of the change made in 4111a4b4955e39d886a348aefc7ea7ae38dfc792.
