### ISSUE TITLE
Modify AB field

### ISSUE THREAD

**Issue by akastrin** [UWNETLAB/metaknowledge#13]
Dear authors,

I need to modify some abstract (AB) fields in my WOS collection (or even add an abstract form MEDLINE if an abstract field is absent). My initial attempt is pasted below. Unfortunately, I first need to copy the `R` object to the `R2` object, which allows me to modify a value. I wonder if there is a way to modify values directly.

```
RC = mk.RecordCollection('download.txt')
R = RC.peek()
R2 = R.copy()
R2._fieldDict['AB'] = ["My abstract."]
```
Best, Andrej

**Comment by tcrick** [comment]
Hi Andrej,

The `_fieldDict` attribute of a `record` is an `OrderedDict`. You can update your entry using `OrderedDict.update()`:

`R._fieldDict.update(AB = 'My abstract.')`

Note that the key `AB` is not a string in this case. Hope this works for you!

**Comment by tcrick** [comment]
Closing - feel free to open a new one if there are still problems.
