### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by lepere-schloop1** [UWNETLAB/metaknowledge#14]
Hello,

I just started using metaknowledge (thank you for developing and maintaining it!) and I've encountered a couple of issues with links embedded in various code subfolders that lead to errors as I'm trying to analyze data using the package.

First, the link to the global gender data in the nameGender.py folder is out of date. The US and UK data are no longer available at https://github.com/networks-lab/globalnamedata/archive/0.3.zip They are now available at https://github.com/OpenGenderTracking/globalnamedata/releases

Second, Web of Science journal abbreviations are no longer available at webpages of the form https://images.webofknowledge.com/images/help/WOS/A_abrvjt.html 
In fact, I have been unable to find journal abbreviations anywhere on the WoS website. 
Old webpages with WoS journal abbreviations are accessible through the internet archive 
https://web.archive.org/web/20200416201003/https://images.webofknowledge.com/images/help/WOS/A_abrvjt.html
but links to internet archive pages do not work well with the current metaknowledge code in backend.py

Hopefully, this information is helpful. While I've found the gender data and tweaked my local metaknowledge code accordingly, I'm hoping that you might be willing the share a version of the journal abbreviations database that you have on hand so that I can move forward with my analysis.

Best,
M

**Comment by tcrick** [comment]
Hi M,

Thanks for bringing this to our attention and sorry for the delay! The gender data link was pointing to the old repository location. I've updated the link and metaknowledge can be updated via pip now. 

As for the Web of Science abbreviations, I am able to open that link in my browser, as well as import the data within metaknowledge, although both were a bit slow. It may be that when you were trying to access them, the webhost was having worse issues. We plan to implement a local backup in a future release.

In the meantime, you can run `metaknowledge.downloadExtras()` manually in your interpreter to make sure that `mk` is able to access the files. It took more than a few seconds for me.

This command should be a bit more visible, probably in the install guide.

**Comment by lepere-schloop1** [comment]
Hello,

Thanks for the response.

Yes, I recently revisited the WoS website and was able to access the webpages with the journal abbreviations by updating the base link in my local code. Seems like the earlier issue was just more COVID chaos!

Thanks for making the metaknowledge.downloadExtras()more visible to future users.  This will definitely be helpful!

Best,
M

Megan LePere-Schloop, MPA, PhD
Assistant Professor
The Ohio State University
John Glenn College of Public Affairs
lepere-schloop.1@osu.edu<mailto:lepere-schloop.1@osu.edu> | (614) 247-6374 office | (614) 292-4868 fax
Pronouns: she/her/hers / Honorific: Dr.

**Comment by tcrick** [comment]
Resolved.
