### ISSUE TITLE
An error about mk

### ISSUE THREAD

**Issue by ctenix** [UWNETLAB/metaknowledge#4]
Sorry, I tried to test the package but I have got an error
My codes is here:
```
import metaknowledge as mk
mk.RecordCollection("data/")
```
When I run the codes above, it told me that module 'metaknowledge' has no attribute 'RecordCollection'.
My compile environment is python 3.6.3 (64 bit in Windows 10 )
Anyone can help me, thanks very much!

**Comment by ConnectedSystems** [comment]
Hi @ctenix 

I'm not part of the development team behind metaknowledge - I've just started using it myself - but I will try to be helpful. 

Based on the error, I suspect that something went wrong during installing the package. Could you let me know how you installed `metaknowledge` and whether any warnings/errors came up?

**Comment by tcrick** [comment]
Closing old issue, feel free to re-open!
